#!/usr/bin/env python3
"""Leaf: the project's lessons, `.aix/custom/skills/core/lessons-learnt-notes/`, and `aix lessons [index|check]`.

A lesson is a correction a user gave an agent about how it works (an assumption it should not make, an action nobody
asked for, a habit to stop). The method lives in the kit skill `core-lessons-learnt`; the content lives here, in the
project layer: one file per lesson under `lessons/` (front matter `rule`, `author`, `scope`, `updated`; body *Why* and
*How to apply*), so two people adding lessons never touch the same file, and a SKILL.md whose index is generated from
those files, never edited by hand. `ensure` creates the notes when they are missing, it never copies them: a kit
upgrade cannot overwrite them; only a custom layer that carries its own copy replaces them (source.install_layer)."""
import re, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from yamlmini import front_matter

NOTES_CLASS = "core-lessons-learnt-notes"
NOTES_REL = Path(".aix") / "custom" / "skills" / "core" / "lessons-learnt-notes"
CAP = 20                       # index lines an agent reads every session; over it, merge or promote (core-lessons-learnt)
FIELDS = ("rule", "author", "scope", "updated")
SCOPES = ("project", "person")
HEAD = f"""---
name: {NOTES_CLASS}
description: The corrections this project's users gave the agents (what not to do, how to behave). Read it before the first action of every session and follow every rule; record new ones with core-lessons-learnt.
---
# {NOTES_CLASS}

Generated by `aix lessons index` from `lessons/*.md`. Never edit this file: add, merge or prune the lesson files with
`core-lessons-learnt`, then run `aix lessons index`. Each line is a rule; open its file for why and when it applies.
`person` lessons are one user's preference: apply them when that author is the one you work with.

"""


def notes_dir(project: Path) -> Path:
    return project / NOTES_REL


def lesson_files(folder: Path) -> list:
    """The lesson files of a notes folder (the project's or a layer source's), sorted by name."""
    base = folder / "lessons"
    return sorted(base.glob("*.md")) if base.is_dir() else []


def is_kit_checkout(project: Path) -> bool:
    """The kit's own checkout ships its .aix/custom/ to every project, so it never holds notes."""
    return (project / "AIX-DEVELOPMENT.md").exists()


def _line(md: Path) -> str:
    fm = front_matter(md)
    return f"- {fm.get('rule', '(no rule)')} ({fm.get('scope', '?')}, {fm.get('author', '?')}) [lessons/{md.name}](lessons/{md.name})"


def render(folder: Path) -> str:
    """SKILL.md text for the notes folder: the fixed head and one index line per lesson."""
    lines = [_line(md) for md in lesson_files(folder)]
    return HEAD + ("\n".join(lines) if lines else "No lessons yet.") + "\n"


def ensure(project: Path) -> bool:
    """Create the empty notes when a project has none (created here, never copied). True when created."""
    folder = notes_dir(project)
    if is_kit_checkout(project) or (folder / "SKILL.md").exists():
        return False
    folder.mkdir(parents=True, exist_ok=True)
    (folder / "SKILL.md").write_text(render(folder), encoding="utf-8")
    print(f"  {NOTES_REL.as_posix()}/SKILL.md -> created (empty lessons)")
    return True


def write_index(project: Path) -> int:
    """Regenerate the SKILL.md index from the lesson files; the number of lessons."""
    folder = notes_dir(project)
    if not folder.is_dir():
        return 0
    (folder / "SKILL.md").write_text(render(folder), encoding="utf-8")
    return len(lesson_files(folder))


def _file_problems(md: Path) -> list:
    fm = front_matter(md)
    out = [f"lessons/{md.name}: no `{k}:` in the front matter" for k in FIELDS if not fm.get(k)]
    if fm.get("scope") and fm["scope"] not in SCOPES:
        out.append(f"lessons/{md.name}: scope `{fm['scope']}` is not one of {', '.join(SCOPES)}")
    body = md.read_text(encoding="utf-8")
    out += [f"lessons/{md.name}: no **{w}:** line" for w in ("Why", "How to apply") if not re.search(rf"\*\*{w}:\*\*", body)]
    return out


def problems(project: Path) -> list:
    """What `aix doctor` and `aix lessons check` report: a stale index, lessons over the cap, malformed lesson files."""
    folder = notes_dir(project)
    if not (folder / "SKILL.md").exists():
        return []
    files = lesson_files(folder)
    out = [p for md in files for p in _file_problems(md)]
    if (folder / "SKILL.md").read_text(encoding="utf-8") != render(folder):
        out.append("the index is stale: run `aix lessons index`")
    if len(files) > CAP:
        out.append(f"{len(files)} lessons, over the cap of {CAP}: merge or promote some (core-lessons-learnt)")
    return out


def main(args):
    from project import find_project
    project = find_project(Path.cwd()) or Path.cwd()
    sub = args[0] if args else "index"
    if sub == "index":
        if is_kit_checkout(project):
            sys.exit("aix lessons: the kit checkout holds no lessons (its .aix/custom/ would ship to every project)")
        ensure(project)
        print(f"  {write_index(project)} lesson(s) indexed in {NOTES_REL.as_posix()}/SKILL.md")
        return
    if sub == "check":
        found = problems(project)
        for p in found:
            print(f"  {p}")
        print(f"  lessons: {len(lesson_files(notes_dir(project)))}, {len(found)} problem(s)")
        sys.exit(1 if found else 0)
    sys.exit("aix lessons: index | check")


if __name__ == "__main__":
    main(sys.argv[1:])
