#!/usr/bin/env python3
"""Road-map helper: create / start / finish tasks and keep going-on/STATE.md in sync.
  roadmap.py new "Title" [--bucket next|backlog|ideas]   -> pending/<bucket>/TASK-0007-title.md
  roadmap.py start TASK-0007                              -> moves to going-on/, sets status, updates STATE.md
  roadmap.py block TASK-0007 "reason"                    -> moves to blocked/, clears active_task
  roadmap.py done  TASK-0007                              -> moves to completed/YYYY-MM/, stamps completion
  roadmap.py list                                         -> one-line summary of every task"""
import re, sys, shutil, datetime, fnmatch
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RM = ROOT / "docs" / "road-map"
TEMPLATE = ROOT / ".aix" / "templates" / "task.md"
sys.path.insert(0, str(Path(__file__).resolve().parent))
import seats


def field(text, key):
    m = re.search(rf"^{key}:\s*(.*?)\s*(#.*)?$", text, re.M)
    return m.group(1).strip() if m else ""


def set_or_add_field(text, key, value):
    """Set a front-matter key; add it before the closing --- when the file predates the key."""
    if re.search(rf"^{key}:", text, re.M):
        return set_field(text, key, value)
    return text.replace("\n---\n", f"\n{key}: {value}\n---\n", 1)


def scope_of(text):
    raw = field(text, "scope").strip("[]")
    return [s.strip().strip("'\"") for s in raw.split(",") if s.strip()]


def overlaps(a, b):
    """Two scope globs collide when one matches the other or one is a prefix folder of the other."""
    a, b = a.rstrip("/"), b.rstrip("/")
    return a == b or fnmatch.fnmatch(a, b) or fnmatch.fnmatch(b, a) or a.startswith(b + "/") or b.startswith(a + "/")


def going_on():
    return sorted((RM / "going-on").glob("TASK-*.md"))


def state_file(seat: str) -> Path:
    """One STATE per seat when the table has more than one seat; the classic STATE.md otherwise."""
    return RM / "going-on" / (f"STATE-{seat}.md" if seats.total(ROOT) > 1 else "STATE.md")


def ensure_state(seat: str) -> Path:
    f = state_file(seat)
    if not f.exists():
        f.write_text((ROOT / ".aix" / "templates" / "session-state.md").read_text(encoding="utf-8"), encoding="utf-8")
    return f


def write_overview():
    """With several seats, STATE.md is the generated overview: every seat, its task, its next action, its heartbeat."""
    if seats.total(ROOT) <= 1:
        return
    lines = ["# Session state — several agents share this repository (generated by aix; your own file is STATE-<seat>.md)", "",
             "| Seat | State | Who | Task | Next action | Heartbeat |", "|---|---|---|---|---|---|"]
    for name, state, tool, who, task, hb in seats.rows(ROOT):
        nxt = ""
        f = RM / "going-on" / f"STATE-{name}.md"
        if f.exists():
            m = re.search(r"^## Immediate next action\n-[ \t]*([^\n]*)$", f.read_text(encoding="utf-8"), re.M)
            nxt = (m.group(1).strip() if m else "")[:60]
        lines.append(f"| {name} | {state.replace(' (you)', '')} | {tool} {who} | {task} | {nxt} | {hb} |")
    lines += ["", "Claim a seat: `aix agent claim`. A task is started with `aix task start ID` and signed by your seat; a task another live seat holds is refused.", ""]
    (RM / "going-on" / "STATE.md").write_text("\n".join(lines), encoding="utf-8")


def all_tasks():
    return sorted(RM.rglob("TASK-*.md"))


def next_id():
    ids = [int(m.group(1)) for p in all_tasks() if (m := re.match(r"TASK-(\d{4})", p.name))]
    return f"TASK-{(max(ids) + 1 if ids else 1):04d}"


def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")[:50]


def set_field(text, key, value):
    return re.sub(rf"^{key}:.*$", f"{key}: {value}", text, count=1, flags=re.M)


def find(tid):
    for p in all_tasks():
        if p.name.startswith(tid):
            return p
    sys.exit(f"{tid} not found")


def cmd_new(title, bucket="next"):
    tid = next_id()
    dst = RM / "pending" / bucket / f"{tid}-{slug(title)}.md"
    t = TEMPLATE.read_text(encoding="utf-8")
    t = set_field(t, "id", tid); t = set_field(t, "title", title)
    t = set_field(t, "created", datetime.date.today().isoformat())
    dst.write_text(t, encoding="utf-8"); print(dst.relative_to(ROOT))


def cmd_start(tid, force=False):
    p = find(tid)
    text = p.read_text(encoding="utf-8")
    seat = seats.claim(ROOT, force)
    owner = field(text, "owner")
    if owner and owner != seat and field(text, "status") == "going-on":
        holder = seats.all_seats(ROOT).get(owner)
        if holder and holder["state"] in ("live", "remote") and not force:
            sys.exit(f"{tid} is held by {owner} ({holder.get('tool')} {holder.get('user')}@{holder.get('host')}, {holder['state']}); pick another task, or --force to take it over")
    my_scope = scope_of(text)
    for other in going_on():
        if other.name.startswith(tid):
            continue
        o = other.read_text(encoding="utf-8")
        hits = [(a, b) for a in my_scope for b in scope_of(o) if overlaps(a, b)]
        if hits:
            print(f"  warning: scope overlaps {other.name[:9]} ({field(o, 'owner') or 'unowned'}): " + ", ".join(f"{a} ~ {b}" for a, b in hits))
    dst = RM / "going-on" / p.name
    t = set_field(text, "status", "going-on")
    t = set_or_add_field(t, "owner", seat)
    t = set_or_add_field(t, "claimed", seats.now())
    _, _, tool = seats.session()
    t = set_or_add_field(t, "claimed_by", f"{tool} {seats.user()}@{seats.host()}")  # who held the seat: readable long after the seat is released
    dst.write_text(t, encoding="utf-8")
    if p != dst:
        p.unlink()
    state = ensure_state(seat)
    s = state.read_text(encoding="utf-8")
    s = set_field(s, "active_task", tid); s = set_field(s, "updated", datetime.datetime.now().isoformat(timespec="minutes"))
    state.write_text(s, encoding="utf-8")
    seats.heartbeat(ROOT, tid); write_overview()
    print(f"{dst.relative_to(ROOT)}  ({seat})")


def cmd_block(tid, reason=""):
    p = find(tid); dst = RM / "blocked" / p.name
    t = set_field(p.read_text(encoding="utf-8"), "status", "blocked")
    t = t.replace("## Decisions / open questions\n", f"## Decisions / open questions\n- BLOCKED {datetime.date.today().isoformat()}: {reason}\n", 1)
    dst.write_text(t, encoding="utf-8"); p.unlink()
    clear_active(tid); seats.heartbeat(ROOT, "none"); write_overview(); print(dst.relative_to(ROOT))


def clear_active(tid):
    for state in [RM / "going-on" / "STATE.md", *(RM / "going-on").glob("STATE-agent-*.md")]:
        if state.exists():
            s = state.read_text(encoding="utf-8")
            if re.search(rf"^active_task:\s*{tid}", s, re.M):
                state.write_text(set_field(s, "active_task", "none"), encoding="utf-8")


def cmd_done(tid):
    p = find(tid); month = datetime.date.today().strftime("%Y-%m")
    dst = RM / "completed" / month / p.name; dst.parent.mkdir(parents=True, exist_ok=True)
    idx = dst.parent / "INDEX.md"   # validate.py requires an INDEX.md in every docs folder
    if not idx.exists():
        idx.write_text(f"# road-map/completed/{month}/\nTasks completed this month, newest last.\n\n| Task | Title | Requirements |\n|---|---|---|\n", encoding="utf-8")
    t = set_field(p.read_text(encoding="utf-8"), "status", "completed")
    t = set_field(t, "completed", datetime.date.today().isoformat())
    dst.write_text(t, encoding="utf-8"); p.unlink()
    clear_active(tid); seats.heartbeat(ROOT, "none"); write_overview(); print(dst.relative_to(ROOT))


def cmd_list():
    tasks = [(p, p.read_text(encoding="utf-8")) for p in all_tasks()]
    for p, t in tasks:
        owner = field(t, "owner")
        print(f"{p.name[:9]}  {field(t, 'status') or '?':10s}  {owner or '':10s} {field(t, 'title') or p.name}")
    warned = set()
    for p, t in tasks:
        if field(t, "status") == "completed":
            continue
        for q, u in tasks:
            if q <= p or field(u, "status") == "completed":
                continue
            hits = [(a, b) for a in scope_of(t) for b in scope_of(u) if overlaps(a, b)]
            if hits and (p.name[:9], q.name[:9]) not in warned:
                warned.add((p.name[:9], q.name[:9]))
                print(f"  overlap: {p.name[:9]} and {q.name[:9]} touch " + ", ".join(f"{a} ~ {b}" for a, b in hits) + " — order them (after:) or merge them")


if __name__ == "__main__":
    a = sys.argv[1:]
    if not a: sys.exit(__doc__)
    if a[0] == "new": cmd_new(a[1], a[3] if len(a) > 3 and a[2] == "--bucket" else "next")
    elif a[0] == "start": cmd_start(a[1], "--force" in a)
    elif a[0] == "block": cmd_block(a[1], a[2] if len(a) > 2 else "")
    elif a[0] == "done": cmd_done(a[1])
    elif a[0] == "list": cmd_list()
    else: sys.exit(__doc__)
